// Copyright the docker-net-dhcp contributors.
// SPDX-License-Identifier: GPL-3.0-only

package plugin

import (
	"encoding/hex"
	"io"
	"strings"
	"testing"

	log "github.com/sirupsen/logrus"
)

const resolvConfMarker = "# generated by docker-net-dhcp from DHCP options"

// fuzzNoControl: the file is line-oriented and unquoted, so a control character changes its structure (#689, #703).
func fuzzNoControl(s string) bool {
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			return false
		}
	}
	return true
}

// fuzzSingleField: whitespace is the field separator, so a value holding one becomes two values (#704).
func fuzzSingleField(s string) bool {
	if s == "" || !fuzzNoControl(s) {
		return false
	}
	f := strings.Fields(s)
	return len(f) == 1 && f[0] == s
}

// FuzzBuildResolvConf: the file has exactly the lines and fields it was asked for (#689, #703, #704).
func FuzzBuildResolvConf(f *testing.F) {
	f.Add("10.99.0.53", "", "example.test", "", "", "eth0")
	// #689: a newline in the single domain appended a line the server chose.
	f.Add("10.99.0.53", "", "", "", "evil.test\nnameserver 6.6.6.6", "eth0")
	// #704: a space in the single domain put the server's domain first.
	f.Add("10.99.0.53", "", "", "", "a.attacker.test b.attacker.test", "eth0")
	// #703: a control character in a server-chosen value.
	f.Add("10.99.0.53\r", "", "", "", "", "eth0")
	// The same two shapes through the search list (#689).
	f.Add("10.99.0.53", "", "a.test b.test", "", "", "eth0")
	f.Add("10.99.0.53", "", "a.test\nnameserver 6.6.6.6", "", "", "eth0")
	// RFC 8106 section 5.1: a link-local resolver from a Router
	// Advertisement, which is the input zonedNameserver exists for (#821).
	f.Add("fe80::1", "10.99.0.53", "", "", "corp.test", "eth0")
	f.Add("", "", "", "", "", "")

	prev := log.StandardLogger().Out
	log.SetOutput(io.Discard)
	f.Cleanup(func() { log.SetOutput(prev) })

	f.Fuzz(func(t *testing.T, ns1, ns2, search1, search2, domain, iface string) {
		dns := []string{ns1, ns2}
		searchList := []string{search1, search2}

		out := string(buildResolvConf(dns, searchList, domain, iface))

		if !strings.HasSuffix(out, "\n") {
			t.Fatalf("resolv.conf does not end in a newline: %q", out)
		}
		lines := strings.Split(strings.TrimSuffix(out, "\n"), "\n")

		if lines[0] != resolvConfMarker {
			t.Fatalf("first line is not the marker: %q", lines[0])
		}

		var wantSearch []string
		for _, s := range searchList {
			if fuzzSingleField(s) {
				wantSearch = append(wantSearch, s)
			}
		}
		if len(wantSearch) == 0 {
			if fields := strings.Fields(domain); fuzzNoControl(domain) && len(fields) > 0 {
				wantSearch = []string{fields[0]}
			}
		}
		var wantDNS []string
		for _, s := range dns {
			if fuzzSingleField(s) {
				wantDNS = append(wantDNS, s)
			}
		}

		body := lines[1:]
		if len(wantSearch) > 0 {
			if len(body) == 0 {
				t.Fatalf("asked for search %v, wrote none: %q", wantSearch, out)
			}
			got, ok := strings.CutPrefix(body[0], "search ")
			if !ok {
				t.Fatalf("line after the marker is not the search line: %q", body[0])
			}
			if fields := strings.Fields(got); len(fields) != len(wantSearch) {
				t.Fatalf("asked for %d search domain(s) %v, wrote %d in %q", len(wantSearch), wantSearch, len(fields), body[0])
			}
			body = body[1:]
		}

		if len(body) != len(wantDNS) {
			t.Fatalf("asked for %d nameserver(s) %v, wrote %d line(s) %q", len(wantDNS), wantDNS, len(body), body)
		}
		for i, line := range body {
			value, ok := strings.CutPrefix(line, "nameserver ")
			if !ok {
				t.Fatalf("line %d is neither a search line nor a nameserver line: %q", i+1, line)
			}
			if fields := strings.Fields(value); len(fields) != 1 {
				t.Fatalf("nameserver line carries %d fields, not one: %q", len(fields), line)
			}
			// zonedNameserver may append "%<iface>" (RFC 4007 section
			// 11) and may not change anything else.
			if !strings.HasPrefix(value, wantDNS[i]) {
				t.Fatalf("nameserver %d is not the address asked for: wrote %q, want it to start with %q", i+1, value, wantDNS[i])
			}
		}
	})
}

func FuzzDeriveHostIfname(f *testing.F) {
	f.Add("web", []byte{0xde, 0xad, 0xbe, 0xef}, []byte{0x01, 0x02, 0x03, 0x04})
	f.Add("/my-container", []byte{0xde, 0xad, 0xbe, 0xef}, []byte{0xde, 0xad, 0xbe, 0xee})
	f.Add("a-very-long-container-name-indeed", []byte{0xde, 0xad, 0xbe, 0xef}, []byte{0x01, 0x02, 0x03, 0x04})
	f.Add("...", []byte{0xde, 0xad}, []byte{})
	f.Add("", []byte{}, []byte{})
	f.Add("ünïcödé-näme", []byte{0xde, 0xad, 0xbe, 0xef}, []byte{0x01, 0x02, 0x03, 0x04})
	f.Add("000000000000 000", []byte{}, []byte{0x00})

	f.Fuzz(func(t *testing.T, source string, epRawA, epRawB []byte) {
		epA := hex.EncodeToString(epRawA)
		epB := hex.EncodeToString(epRawB)

		got := deriveHostIfname(source, epA)

		// Steps 1 and 2 of the rule in docs/reference.md, over bytes: an interface name is bytes to the kernel (#978).
		mapped := make([]byte, 0, len(source))
		for i := 0; i < len(source); i++ {
			c := source[i]
			switch {
			case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9',
				c == '.', c == '-', c == '_':
				mapped = append(mapped, c)
			default:
				mapped = append(mapped, '-')
			}
		}
		for len(mapped) > 0 && !fuzzAlnum(mapped[0]) {
			mapped = mapped[1:]
		}
		model := string(mapped)

		switch {
		case model == "":
			if got != "" {
				t.Fatalf("nothing legal was left of %q, yet the link was named %q", source, got)
			}
			return
		case len(model) <= hostIfnameMaxLen:
			if got != model {
				t.Fatalf("short name: got %q, the rule gives %q for %q", got, model, source)
			}
			if other := deriveHostIfname(source, epB); other != got {
				t.Fatalf("a short name took the endpoint id into account: %q vs %q", got, other)
			}
			return
		}

		suffix := epA
		if len(suffix) > hostIfnameSuffixLen {
			suffix = suffix[:hostIfnameSuffixLen]
		}
		want := model[:hostIfnameMaxLen]
		if suffix != "" {
			want = model[:hostIfnameMaxLen-1-len(suffix)] + "-" + suffix
		}
		if got != want {
			t.Fatalf("truncated name: got %q, the rule gives %q for %q with endpoint %q", got, want, source, epA)
		}
		if len(got) > hostIfnameMaxLen {
			t.Fatalf("name is %d bytes, over the %d the kernel takes: %q", len(got), hostIfnameMaxLen, got)
		}

		// Plain truncation can equal a suffixed name only when the endpoint id is empty; the one caller passes a
		// 64-hex libnetwork id, so the seed above is unreachable (#978, #1010).
		otherSuffix := epB
		if len(otherSuffix) > hostIfnameSuffixLen {
			otherSuffix = otherSuffix[:hostIfnameSuffixLen]
		}
		if otherSuffix != suffix && suffix != "" && otherSuffix != "" {
			if other := deriveHostIfname(source, epB); other == got {
				t.Fatalf("endpoints %q and %q both took the name %q", epA, epB, got)
			}
		}
	})
}

func fuzzAlnum(c byte) bool {
	return c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9'
}

// libnetwork stores the PoolID and replays it at every daemon start (controller.go reservePools), so the id
// must be deterministic and must decode back to its request (#110, #1010).
func FuzzIPAMPoolIDRoundTrip(f *testing.F) {
	f.Add(false, "192.168.100.0/24", "eth0", "", true, false)
	f.Add(false, "192.168.100.0/24", "", "br-lan", false, true)
	f.Add(true, "10.1.2.3/8", "", "", false, false)
	f.Add(false, "", "eth0", "br-lan", true, true)
	f.Add(false, "192.168.100.0/24", "", "", true, false)
	f.Add(true, "", "", "", false, true)

	f.Fuzz(func(t *testing.T, global bool, pool, parent, bridge string, withParent, withBridge bool) {
		space := ipamLocalAddressSpace
		if global {
			space = ipamGlobalAddressSpace
		}
		opts := map[string]string{}
		if withParent {
			opts["parent"] = parent
		}
		if withBridge {
			opts["bridge"] = bridge
		}

		id, err := ipamPoolID(space, pool, opts)
		if err != nil {
			return
		}

		if again, err := ipamPoolID(space, pool, opts); err != nil || again != id {
			t.Fatalf("one request derived two identities: %q then %q (err %v)", id, again, err)
		}
		if !strings.HasPrefix(id, ipamPoolIDPrefix) {
			t.Fatalf("pool id %q does not carry this driver's prefix", id)
		}

		key, name := ipamPoolIDNames(id)
		if len(opts) == 0 {
			if key != "" || name != "" {
				t.Fatalf("pool id %q was minted with no option and decoded to %s=%q", id, key, name)
			}
			return
		}
		if key == "" {
			t.Fatalf("pool id %q was minted from %v and decoded to no option at all", id, opts)
		}
		if want, ok := opts[key]; !ok || want != name {
			t.Fatalf("pool id %q decoded to %s=%q, which is not what it was minted from: %v", id, key, name, opts)
		}
		if !strings.HasSuffix(id, "/"+key+"="+name) {
			t.Fatalf("pool id %q does not end in the option it decoded to, %s=%q", id, key, name)
		}
		for k := range opts {
			if k != key {
				t.Fatalf("pool id %q was minted from %v and the %s half cannot be read back", id, opts, k)
			}
		}
	})
}
