// Copyright the docker-net-dhcp contributors.
// SPDX-License-Identifier: GPL-3.0-only

package plugin

import (
	"encoding/hex"
	"io"
	"strings"
	"testing"

	log "github.com/sirupsen/logrus"
)

// resolvConfMarker is the first line buildResolvConf writes. Spelled out
// here rather than imported from the subject: a target that took the
// constant from the code under test would follow it through a rename
// and stop pinning anything.
const resolvConfMarker = "# generated by docker-net-dhcp from DHCP options"

// fuzzNoControl is the #689 and #703 half of the rule, restated: the
// file is line-oriented and unquoted, so a control character in a value
// changes the structure of the file rather than the value.
func fuzzNoControl(s string) bool {
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			return false
		}
	}
	return true
}

// fuzzSingleField is the whole rule a resolv.conf value has to satisfy
// to occupy one field of one line, stated as the property rather than
// taken from the subject.
//
// The second half is #704: whitespace is this sink's field separator,
// so a value carrying one becomes two values. dhcp.SafeValue rejects
// r < 0x20, which stops one character short of the space at 0x20 — the
// comment on dhcp.FirstSearchDomain says so in as many words.
func fuzzSingleField(s string) bool {
	if s == "" || !fuzzNoControl(s) {
		return false
	}
	f := strings.Fields(s)
	return len(f) == 1 && f[0] == s
}

// FuzzBuildResolvConf holds the renderer to the shape of the file it
// writes, for any values a DHCP server can put in a lease.
//
// The invariant is the one three issues were about and no table can
// state: the file has exactly the lines it was asked for and not one
// more. #689 found a newline in option 15 appending a whole line, #703
// found the four string-typed options passing control characters
// through, #704 found a space in option 15 turning one search domain
// into several with the server's first. Every one of those is "the
// output has a line, or a field, the caller did not ask for", which is
// a property of the rendering and not of any particular option value.
//
// The oracle is built here from the rule and not from the subject:
// fuzzSingleField is a second statement of what may occupy a field, so a
// change to dhcp.SafeValue that widened it would fail this target rather
// than travel with it.
//
// BOUND: the dns and search lists are two entries wide. A defect that
// needs three entries to appear is outside what this target can see;
// the count invariant below is what makes two enough for a miscount.
func FuzzBuildResolvConf(f *testing.F) {
	f.Add("10.99.0.53", "", "example.test", "", "", "eth0")
	// #689: a newline in the single domain appended a line the server chose.
	f.Add("10.99.0.53", "", "", "", "evil.test\nnameserver 6.6.6.6", "eth0")
	// #704: a space in the single domain put the server's domain first.
	f.Add("10.99.0.53", "", "", "", "a.attacker.test b.attacker.test", "eth0")
	// #703: a control character in a server-chosen value.
	f.Add("10.99.0.53\r", "", "", "", "", "eth0")
	// The same two shapes through the search LIST, which is the channel
	// #689 called structurally safe because of its caller.
	f.Add("10.99.0.53", "", "a.test b.test", "", "", "eth0")
	f.Add("10.99.0.53", "", "a.test\nnameserver 6.6.6.6", "", "", "eth0")
	// RFC 8106 section 5.1: a link-local resolver from a Router
	// Advertisement, which is the input zonedNameserver exists for (#821).
	f.Add("fe80::1", "10.99.0.53", "", "", "corp.test", "eth0")
	// Nothing at all, and a zone with no interface to name.
	f.Add("", "", "", "", "", "")

	// resolvSafe warns on every dropped value, which is one line of
	// stderr per iteration and the difference between a fuzz run and a
	// log transcript. The assertions read the returned bytes.
	prev := log.StandardLogger().Out
	log.SetOutput(io.Discard)
	f.Cleanup(func() { log.SetOutput(prev) })

	f.Fuzz(func(t *testing.T, ns1, ns2, search1, search2, domain, iface string) {
		dns := []string{ns1, ns2}
		searchList := []string{search1, search2}

		out := string(buildResolvConf(dns, searchList, domain, iface))

		if !strings.HasSuffix(out, "\n") {
			t.Fatalf("resolv.conf does not end in a newline: %q", out)
		}
		lines := strings.Split(strings.TrimSuffix(out, "\n"), "\n")

		if lines[0] != resolvConfMarker {
			t.Fatalf("first line is not the marker: %q", lines[0])
		}

		// What the renderer was asked for, derived here.
		var wantSearch []string
		for _, s := range searchList {
			if fuzzSingleField(s) {
				wantSearch = append(wantSearch, s)
			}
		}
		if len(wantSearch) == 0 {
			// Option 15 is taken whole, so the control-character rule
			// applies to the whole value and only then is the first
			// domain kept (resolvconf.go, and dhcp.FirstSearchDomain).
			if fields := strings.Fields(domain); fuzzNoControl(domain) && len(fields) > 0 {
				wantSearch = []string{fields[0]}
			}
		}
		var wantDNS []string
		for _, s := range dns {
			if fuzzSingleField(s) {
				wantDNS = append(wantDNS, s)
			}
		}

		body := lines[1:]
		if len(wantSearch) > 0 {
			if len(body) == 0 {
				t.Fatalf("asked for search %v, wrote none: %q", wantSearch, out)
			}
			got, ok := strings.CutPrefix(body[0], "search ")
			if !ok {
				t.Fatalf("line after the marker is not the search line: %q", body[0])
			}
			if fields := strings.Fields(got); len(fields) != len(wantSearch) {
				t.Fatalf("asked for %d search domain(s) %v, wrote %d in %q", len(wantSearch), wantSearch, len(fields), body[0])
			}
			body = body[1:]
		}

		if len(body) != len(wantDNS) {
			t.Fatalf("asked for %d nameserver(s) %v, wrote %d line(s) %q", len(wantDNS), wantDNS, len(body), body)
		}
		for i, line := range body {
			value, ok := strings.CutPrefix(line, "nameserver ")
			if !ok {
				t.Fatalf("line %d is neither a search line nor a nameserver line: %q", i+1, line)
			}
			if fields := strings.Fields(value); len(fields) != 1 {
				t.Fatalf("nameserver line carries %d fields, not one: %q", len(fields), line)
			}
			// zonedNameserver may append "%<iface>" (RFC 4007 section
			// 11) and may not change anything else.
			if !strings.HasPrefix(value, wantDNS[i]) {
				t.Fatalf("nameserver %d is not the address asked for: wrote %q, want it to start with %q", i+1, value, wantDNS[i])
			}
		}
	})
}

// FuzzDeriveHostIfname holds the host-side link name to the rule
// docs/reference.md states, for any container name or hostname.
//
// The source is attacker-supplied in this repo's own threat model:
// hostIfnameSource re-applies dhcp.SafeValue to a container's
// --hostname before this function sees it, for exactly that reason.
// deriveHostIfname then has to turn arbitrary bytes into something the
// kernel accepts, deterministically, because an operator is told in
// words what name to expect.
//
// The oracle is a second statement of steps 1 to 3 of that documented
// rule, written from the prose rather than copied from the code, so a
// change to either half shows up as a divergence. Asserting
// dhcp.ValidIfaceName on the result would be a check with one possible
// verdict: the function ends by applying it.
//
// BOUND: the endpoint id is hex, which is the shape libnetwork mints.
// An endpoint id carrying a character an interface name may not is not
// driven here, and the model would not be exact for one.
func FuzzDeriveHostIfname(f *testing.F) {
	f.Add("web", []byte{0xde, 0xad, 0xbe, 0xef}, []byte{0x01, 0x02, 0x03, 0x04})
	f.Add("/my-container", []byte{0xde, 0xad, 0xbe, 0xef}, []byte{0xde, 0xad, 0xbe, 0xee})
	f.Add("a-very-long-container-name-indeed", []byte{0xde, 0xad, 0xbe, 0xef}, []byte{0x01, 0x02, 0x03, 0x04})
	f.Add("...", []byte{0xde, 0xad}, []byte{})
	f.Add("", []byte{}, []byte{})
	f.Add("ünïcödé-näme", []byte{0xde, 0xad, 0xbe, 0xef}, []byte{0x01, 0x02, 0x03, 0x04})
	// A source that already ends in the shape step 3 appends. The two
	// names below are equal, and the endpoint that has no id is why;
	// see the collision assertion.
	f.Add("000000000000 000", []byte{}, []byte{0x00})

	f.Fuzz(func(t *testing.T, source string, epRawA, epRawB []byte) {
		epA := hex.EncodeToString(epRawA)
		epB := hex.EncodeToString(epRawB)

		got := deriveHostIfname(source, epA)

		// Steps 1 and 2 of the documented rule: every byte outside the
		// name rule becomes '-', then leading bytes that are not
		// alphanumeric are dropped. Bytes, not runes: an interface name
		// is bytes to the kernel and a multi-byte rune is several.
		mapped := make([]byte, 0, len(source))
		for i := 0; i < len(source); i++ {
			c := source[i]
			switch {
			case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9',
				c == '.', c == '-', c == '_':
				mapped = append(mapped, c)
			default:
				mapped = append(mapped, '-')
			}
		}
		for len(mapped) > 0 && !fuzzAlnum(mapped[0]) {
			mapped = mapped[1:]
		}
		model := string(mapped)

		switch {
		case model == "":
			if got != "" {
				t.Fatalf("nothing legal was left of %q, yet the link was named %q", source, got)
			}
			return
		case len(model) <= hostIfnameMaxLen:
			// Step 3 does not apply, so the endpoint may not reach the
			// name: two endpoints of one container image get the same
			// short name and that is the documented answer.
			if got != model {
				t.Fatalf("short name: got %q, the rule gives %q for %q", got, model, source)
			}
			if other := deriveHostIfname(source, epB); other != got {
				t.Fatalf("a short name took the endpoint id into account: %q vs %q", got, other)
			}
			return
		}

		// Step 3: the name keeps its first bytes and ends in '-' plus
		// the endpoint id's first five, so two long names sharing a
		// prefix do not become one name.
		suffix := epA
		if len(suffix) > hostIfnameSuffixLen {
			suffix = suffix[:hostIfnameSuffixLen]
		}
		want := model[:hostIfnameMaxLen]
		if suffix != "" {
			want = model[:hostIfnameMaxLen-1-len(suffix)] + "-" + suffix
		}
		if got != want {
			t.Fatalf("truncated name: got %q, the rule gives %q for %q with endpoint %q", got, want, source, epA)
		}
		if len(got) > hostIfnameMaxLen {
			t.Fatalf("name is %d bytes, over the %d the kernel takes: %q", len(got), hostIfnameMaxLen, got)
		}

		// The collision the suffix exists to prevent: endpoints that
		// differ inside the five bytes that reach the name must not
		// produce one name for one source.
		//
		// BOTH ENDPOINTS, because an absent one is a different rule and
		// not a worse outcome of this one. deriveHostIfname has an
		// explicit suffix == "" arm that truncates and appends nothing,
		// and a name made by plain truncation can equal a suffixed name
		// whenever the source already looks like one: this target found
		// "000000000000 000" taking "000000000000-00" under both the
		// empty endpoint and endpoint "00" (60s run, 904461 execs), and
		// that pair is the seed above. It is not reachable: the only
		// caller passes m.joinReq.EndpointID (host_ifname.go:207), which
		// libnetwork mints as 64 hex characters. Between two endpoints
		// that HAVE ids the property holds and is not vacuous — the
		// suffix is hex, so it can never supply the '-' the shorter
		// name would need at the joining position.
		otherSuffix := epB
		if len(otherSuffix) > hostIfnameSuffixLen {
			otherSuffix = otherSuffix[:hostIfnameSuffixLen]
		}
		if otherSuffix != suffix && suffix != "" && otherSuffix != "" {
			if other := deriveHostIfname(source, epB); other == got {
				t.Fatalf("endpoints %q and %q both took the name %q", epA, epB, got)
			}
		}
	})
}

func fuzzAlnum(c byte) bool {
	return c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9'
}

// FuzzIPAMPoolIDRoundTrip holds the pool identity to the two properties
// the driver's binding depends on.
//
// A PoolID is the whole identity of an address pool. libnetwork stores
// the string this driver returned and replays it at every daemon start
// (moby libnetwork/controller.go, reservePools), so the driver has to
// derive the same string from the same request forever — that is the
// first property, and the reason ipamPoolOptKeys is a slice and not a
// map (ipam_pool.go:40-50).
//
// The second is that the string is read back: RequestPool decodes the
// interface name out of the id it just minted (ipam.go:182) and
// CreateNetwork compares that name against the network's own -o parent=
// or -o bridge=. An option the encoder accepted and the decoder cannot
// see is an identity two different requests share, which is the exact
// defect the refusal of unknown keys already exists to prevent.
// THE ADDRESS SPACE IS A BOOL AND NOT A STRING, and that is the
// difference between this target and a target that runs a million
// iterations of nothing. ipamPoolID refuses any space but its own two
// before it does anything else, and the first draft of this seeded them
// as "local" and "global" — libnetwork's names, not this driver's
// ("dhcp-local", ipam_pool.go:20). Every seed returned at the first
// line, the fuzzer had no path past it, and the target passed 60s and
// 1339795 execs having asserted nothing. Choosing between the two
// constants makes an empty domain unreachable rather than unlikely, and
// takes the constants by identifier so a rename moves the inputs with
// it. That is the opposite choice from resolvConfMarker above, and on
// purpose: this is input selection, which must follow a rename, while
// the marker is an asserted value, which must not.
//
// The refusal of an unknown address space keeps its unit test
// (TestIPAMPoolID in ipam_pool_test.go); it is not this target's job.
func FuzzIPAMPoolIDRoundTrip(f *testing.F) {
	f.Add(false, "192.168.100.0/24", "eth0", "", true, false)
	f.Add(false, "192.168.100.0/24", "", "br-lan", false, true)
	f.Add(true, "10.1.2.3/8", "", "", false, false)
	f.Add(false, "", "eth0", "br-lan", true, true)
	f.Add(false, "192.168.100.0/24", "", "", true, false)
	f.Add(true, "", "", "", false, true)

	f.Fuzz(func(t *testing.T, global bool, pool, parent, bridge string, withParent, withBridge bool) {
		space := ipamLocalAddressSpace
		if global {
			space = ipamGlobalAddressSpace
		}
		opts := map[string]string{}
		if withParent {
			opts["parent"] = parent
		}
		if withBridge {
			opts["bridge"] = bridge
		}

		id, err := ipamPoolID(space, pool, opts)
		if err != nil {
			return
		}

		if again, err := ipamPoolID(space, pool, opts); err != nil || again != id {
			t.Fatalf("one request derived two identities: %q then %q (err %v)", id, again, err)
		}
		if !strings.HasPrefix(id, ipamPoolIDPrefix) {
			t.Fatalf("pool id %q does not carry this driver's prefix", id)
		}

		key, name := ipamPoolIDNames(id)
		if len(opts) == 0 {
			if key != "" || name != "" {
				t.Fatalf("pool id %q was minted with no option and decoded to %s=%q", id, key, name)
			}
			return
		}
		if key == "" {
			t.Fatalf("pool id %q was minted from %v and decoded to no option at all", id, opts)
		}
		if want, ok := opts[key]; !ok || want != name {
			t.Fatalf("pool id %q decoded to %s=%q, which is not what it was minted from: %v", id, key, name, opts)
		}
		if !strings.HasSuffix(id, "/"+key+"="+name) {
			t.Fatalf("pool id %q does not end in the option it decoded to, %s=%q", id, key, name)
		}
		for k := range opts {
			if k != key {
				t.Fatalf("pool id %q was minted from %v and the %s half cannot be read back", id, opts, k)
			}
		}
	})
}
